name: noorapp
description: Professional WebView App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ویب ویو اور میڈیا ہینڈلنگ کے لیے
  flutter_inappwebview: ^6.0.0
  # کیمرہ اور گیلری پرمیشنز کے لیے
  permission_handler: ^11.0.0
  # واٹس ایپ یا بیرونی لنکس کھولنے کے لیے
  url_launcher: ^6.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - support.png
    - whatsapp.png
