name: Build Final Islam Guide
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # یہاں ہم نے Node.js 24 کو زبردستی نافذ کر دیا ہے تاکہ مستقبل کی وارننگ ختم ہو جائے
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # تازہ ترین فلٹر ورژن کا استعمال تاکہ نئے اینڈرائیڈ ورژن سپورٹ ہوں
          flutter-version: '3.22.0' 
      
      - name: Clean & Get Packages
        run: |
          flutter clean
          flutter pub get
      
      - name: Force Generate Icons
        run: flutter pub run flutter_launcher_icons

      - name: Build Optimized APK
        # ہم نے یہاں ہدف (Target) اینڈرائیڈ ورژن کو بھی مدنظر رکھا ہے
        run: flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Islam-Guide-Final
          path: build/app/outputs/flutter-apk/*.apk
